version: "3"
services:
  app:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
  ui:
    build: ui/scrapegoat-ui
    ports:
      - "8080:8080"
    volumes:
      - ./ui/scrapegoat-ui:/ui
